[package]
name = "blog_os"
version = "0.1.0"
edition = "2024"

[dependencies]
x86_64 = "0.15.2"
pc-keyboard = "0.8.0"
pic8259 = "0.10.1"

bootloader = "0.9"
volatile = "0.2.6"
spin = "0.5.2"
[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]

[[bin]]

name = "blog_os"
test = false
bench = false
